### ISSUE TITLE
embeds

### ISSUE THREAD

**Issue by Codfish246** [VulcanGDL/DevBot#3]
needs embed because embeds noice

**Comment by Codfish246** [comment]
whops forgot to mark as to-do xd

**Comment by VulcanGDL** [comment]
embed the help command and send it throught DM

**Comment by Codfish246** [comment]
maybe a separate command for help through dm? or when help gets big send it only through dm @VulcanGDL

**Comment by VulcanGDL** [comment]
ye if you want to do that with your embed task 😛

**Comment by VulcanGDL** [comment]
gitlab transfer
